### PR TITLE
LIFX: improve performance of multi-light transitions

### PR DESCRIPTION
**Pull request by amelchio**

### CODE REVIEW

**Comment by amelchio** [comment]
@acantril Can you test this version for improved performance with your multi-dozen LIFX setup?

**Comment by acantril** [comment]
Will do - I'll update you with findings.

**Comment by amelchio** [comment]
@acantril Do you have an ETA on this? :-)

**Comment by acantril** [comment]
Testing right now @amelchio

**Comment by acantril** [comment]
Initial commants.
1) it seems like things are either happening in parallel or with much less gap between - the whole house 'feels' like it changes again .. 
2) i was getting errors before if i attempted to rapidly move between 3-4 scenes with all the bulbs in ... action in progress... dont have that anymore.

**Comment by acantril** [comment]
@amelchio ill keep testing, but it feels much better.

**Comment by acantril** [comment]
full house scene change down to like 6 seconds (previously around that, up to 30 secs or so with the recent change)

**Comment by amelchio** [comment]
Thanks @acantril for testing, much appreciated. It seems we are at least back to baseline.

It should all happen in parallel now so I actually think 6 seconds is a bit much for a scene change. I figured it should be done in about 1-2 seconds but maybe I am being too optimistic – your LIFX setup is quite bigger than mine.

I did find some useless chatter and have pushed a couple of commits to remove that. Feel free to test those as well (if you don't have time, that's fine – I can test this myself, just not at your scale).

**Comment by acantril** [comment]
6 seconds could have been my fault ... i had a 3s transition in there. So its actually close to 2-3 seconds now @amelchio

**Comment by amelchio** [comment]
Well that 3s transition should also be in parallel, so it should not delay the other bulbs.

**Comment by acantril** [comment]
It doesnt that what i mean... i have 3s on all the bulbs in the scene... so the whole thing takes 3s longer than it should. Removing that, with a raw scene.. and everything completes at the same time, very quickly. Tl;dr seems all good @amelchio

**Comment by amelchio** [comment]
Great, thank you very much.

**Pull request closed without merging**
